### ISSUE TITLE
Can't install cytofkit2 in Rstudio

### ISSUE THREAD

**Issue by cseligman** [JinmiaoChenLab/cytofkit2#32]
<if(!require(devtools)){
  install.packages("devtools") # If not already installed
devtools::install_github("JinmiaoChenLab/cytofkit2")

> devtools::install_github("JinmiaoChenLab/cytofkit2")
}
Downloading GitHub repo JinmiaoChenLab/cytofkit2@HEAD
Skipping 1 packages not available: destiny
√  checking for file 'C:\Users\chets\AppData\Local\Temp\Rtmp2BDSst\remotes31145fc6431f\JinmiaoChenLab-cytofkit2-b9ed958/DESCRIPTION' (885ms)
-  preparing 'cytofkit2': (2.9s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (1s)
-  checking for empty or unneeded directories
-  building 'cytofkit2_0.99.53.tar.gz'
   
ERROR: dependency 'destiny' is not available for package 'cytofkit2'
* removing 'C:/Program Files/R/R-4.1.0/library/cytofkit2'
Warning in i.p(...) :
  installation of package ‘C:/Users/chets/AppData/Local/Temp/Rtmp2BDSst/file3114b6a5a4e/cytofkit2_0.99.53.tar.gz’ had non-zero exit status
> 
**I was unable to install "destiny" either as in (https://www.bioconductor.org/packages/release/bioc/html/destiny.html)**
<if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("destiny")>

'getOption("repos")' replaces
Bioconductor standard repositories,
see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

Bioconductor version 3.13
  (BiocManager 1.30.16), R 4.1.0
  (2021-05-18)
Installing package(s) 'destiny'
Warning in .inet_warning(msg) :
  package ‘destiny’ is not available for Bioconductor version '3.13'

**Comment by raman91** [comment]
We have fixed it. Please try to install again

**Comment by cseligman** [comment]
Thank you, cytofkit2 Version: 0.99.53 was installed with ease.
